### ISSUE TITLE
Document requirements of a basic CSI plugin

### ISSUE THREAD

**Issue by mbtamuli** [mbtamuli/csi-quickstart#3]
# Goal
- [x] Should the basic CSI plugin emulate [`emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) or [`hostPath`](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume. - Update [./README.md](https://github.com/mbtamuli/csi-quickstart/blob/main/README.md?plain=1#L6) with decision and reasoning. - #5 
- [x] Clear requirements for a ~`<TBD type>`~ CSI plugin simulating [`emptyDir`](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir). - #6 
- [x] Any additional diagram or commentary explaining unclear parts of Specification.  - #6 

# Approach
- Reading material
  - https://kubernetes-csi.github.io/docs/
  - https://github.com/kubernetes-csi/csi-driver-host-path
  - https://github.com/rexray/gocsi/tree/master/csc
  - https://arslan.io/2018/06/21/how-to-write-a-container-storage-interface-csi-plugin/
